### ISSUE TITLE
Support timeout 

### ISSUE THREAD

**Issue by ph4r5h4d** [erikogan/wait4ports#2] opened 2019-05-08 07:36 UTC
It would be great it supports for timeout would be added to the project.
In case a time out is reached the application should exit with a non-zero status code.

**Comment by thisismydesign** [comment] 2020-01-24 10:52
This project is the only option I know of that is available via `apk add`. But no support for timeouts keeps me from using it. 

Meanwhile, I'm pretty sure you can do something like
`timeout 10 wait4ports redis:6379  || exit 1`

But if I have to write that I might as well use a one-liner for waiting ports instead of installing this dependency.

**Comment by erikogan** [comment] 2020-02-19 19:32
I don’t know how I missed the notification for this issue. I agree it would be better if wait4ports supported setting a timeout instead of waiting forever. It should be easy enough to add. I’ll look into that this weekend.

**Comment by ph4r5h4d** [comment] 2020-02-23 19:06
Since it's been a long time, I started to work on a similar project. Maybe you take a look as well.
https://github.com/ph4r5h4d/wait4it

**Comment by erikogan** [comment] 2020-02-27 18:11
Quick update: I added the code for this change this morning, but testing revealed an unrelated segfault. I didn’t have time to debug that issue, but I should tonight / tomorrow morning.

**Comment by erikogan** [comment] 2020-03-21 17:02
“Life is what happens to you while you’re busy making other plans.”

This morning I realized I’d never closed the loop on this. I dug into the SEGV, even though I could not reproduce it on AlpineLinux. I’ve fixed it and merged the timeout options to master.

I’ll post an AlpineLinux package once I remember how, and work on adding a debian package as well.

**Comment by erikogan** [comment] 2020-03-21 21:36
Alpine has moved from Github to their own GitLab instance. You can follow along at the [0.3.1 Merge Request](https://gitlab.alpinelinux.org/alpine/aports/merge_requests/5667).

I’m going to close this issue, and look at also building a debian package.

**Closed as completed by erikogan** 2020-03-21 21:36 UTC
